services:
  bun-pokemon-web-server:
    image: bun-pokemon-web-server:latest
    container_name: bun-pokemon-web-server
    build:
      context: .
      dockerfile: Dockerfile.bun.web
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    expose:
      - '3000'
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      neo4j:
        condition: service_healthy
        restart: true
      rs-tcg-api:
        condition: service_healthy
        restart: true
    env_file:
      - ./apps/web/.env
    networks:
      - pika