services:
  rs-tcg-api:
    image: rs-tcg-api:latest
    container_name: rs-tcg-api
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - '8080'
    ports:
      - "8080:8080"
    networks:
      - pika